### ISSUE TITLE
[Suggestion] Add to choose local file. Optionally add Seafile, and DAV

### ISSUE THREAD

**Issue by droidzone** [perfectapi/CKP#163]
Currently the plugin allows to only do a one-time upload of a local file. Which is rather weird because this makes sense only if the plugin needs to offload this data somewhere externally. It should allow for accessing a local database and keyfile continually, and store relevant data locally. Otherwise end user doesnt get an option to use the plethora of cloud providers currently unsupported by the plugin. Endusers should have a choice of selecting their cloud provider, or at least choose to sync their data in the way they require. For example I use Seafile, Syncthing and DAV options to my own dedicated server. But the extension doesnt support that. So, please allow local upload and storing data and key file.

**Comment by DukeyToo** [comment]
The ability to choose a local file is not supported by Chrome extensions - CPK cannot reach out to the hard drive of the user - it would be a huge security risk if it could.  That is why the user must upload the file - the file is stored in Chrome internal storage then, and owned by the extension, so nothing else can get to it.

Other cloud providers are possible, and pull requests are welcome.  There is a current PR https://github.com/perfectapi/CKP/pull/98 that adds WebDAV support, but I have had limited success testing it, which is why it is not yet in the released product.
