### ISSUE TITLE
Help - Restore the database from CKP plugin ????!!!

### ISSUE THREAD

**Issue by khaangelled** [perfectapi/CKP#84]
Main database has been damaged and did not promise I can open it, but the database is still working in the plugin. I want a way to recover the data from the plugin base. Or a link to open a location database

**Comment by DukeyToo** [comment]
I think what you are saying is that you uploaded your database to CKP, and now want to extract it out again? I suppose it is possible, but it is not a common enough request that I would code that feature. 

 If you have some coding skills you could do it yourself, but otherwise, I expect you are out of luck.

**Comment by khaangelled** [comment]
can you help about the code . or how can export the database ?

**Comment by DukeyToo** [comment]
http://stackoverflow.com/questions/3665115/create-a-file-in-memory-for-user-to-download-not-through-server may help.  If your file is stored in CKP, then you can see the encoded file in CKP Options/Stored Data - it will be the looong string of letters and numbers.  Copy that value, excluding quotes, and use the answer from the stackoverflow to extract it.

In theory that should work.

**Comment by khaangelled** [comment]
thanks , I'll try with this way . ^_^
